import { defineConfig } from "vitepress";

const SITE_DESCRIPTION =
  "Explicit errors as values for TypeScript, with a separate defect channel for the unexpected and qualification enforced at every boundary.";

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: "unthrown",
  description: SITE_DESCRIPTION,
  base: "/unthrown/",
  lang: "en-US",
  cleanUrls: true,

  // The API reference under /api/ is generated by TypeDoc and copied in at build
  // time; its cross-references use relative links TypeDoc resolves itself.
  ignoreDeadLinks: [/^\/api\//, /^\.\/index$/, /^\.\/[a-z-]+$/, /^\.\.\//],

  sitemap: {
    hostname: "https://btravers.github.io/unthrown/",
  },

  // Exclude internal design docs from the published site.
  srcExclude: ["design-memory.md", "superpowers/**", "README.md"],

  themeConfig: {
    nav: [
      { text: "Guide", link: "/guide/why-unthrown" },
      { text: "API", link: "/api/" },
      {
        text: "Changelog",
        link: "https://github.com/btravers/unthrown/releases",
      },
    ],

    sidebar: {
      "/guide/": [
        {
          text: "Introduction",
          items: [
            { text: "Why unthrown?", link: "/guide/why-unthrown" },
            { text: "Getting Started", link: "/guide/getting-started" },
            { text: "Core Concepts", link: "/guide/core-concepts" },
          ],
        },
        {
          text: "Working with Results",
          items: [
            { text: "The Defect Channel", link: "/guide/the-defect-channel" },
            { text: "Boundaries & Qualification", link: "/guide/boundaries" },
            { text: "Async Results", link: "/guide/async-results" },
          ],
        },
        {
          text: "Error Modeling",
          items: [{ text: "Tagged Errors", link: "/guide/tagged-errors" }],
        },
        {
          text: "Ecosystem",
          items: [
            { text: "Testing", link: "/guide/testing" },
            { text: "Pattern Matching", link: "/guide/pattern-matching" },
          ],
        },
      ],
      "/api/": [
        {
          text: "API Reference",
          items: [
            { text: "Overview", link: "/api/" },
            { text: "unthrown", link: "/api/core/" },
            { text: "@unthrown/vitest", link: "/api/vitest/" },
            { text: "@unthrown/pattern", link: "/api/pattern/" },
          ],
        },
      ],
    },

    socialLinks: [
      { icon: "github", link: "https://github.com/btravers/unthrown" },
      { icon: "npm", link: "https://www.npmjs.com/package/unthrown" },
    ],

    footer: {
      message: "Released under the MIT License.",
      copyright: `Copyright © ${new Date().getFullYear()} Benoit TRAVERS`,
    },

    search: {
      provider: "local",
    },

    editLink: {
      pattern: "https://github.com/btravers/unthrown/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },
  },

  head: [
    ["meta", { name: "author", content: "Benoit TRAVERS" }],
    ["meta", { name: "robots", content: "index, follow" }],
    [
      "meta",
      {
        name: "keywords",
        content:
          "typescript, result, error handling, errors as values, neverthrow, effect, railway oriented programming, tagged error, defect, panic, type-safe",
      },
    ],
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:site_name", content: "unthrown" }],
    ["meta", { property: "og:title", content: "unthrown" }],
    ["meta", { property: "og:description", content: SITE_DESCRIPTION }],
    ["meta", { name: "twitter:card", content: "summary" }],
  ],
});
