import { defineConfig } from "vitepress";

const SITE_DESCRIPTION =
  "Explicit errors as values for TypeScript, with a separate defect channel for the unexpected and qualification enforced at every boundary.";

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: "unthrown",
  description: SITE_DESCRIPTION,
  base: "/unthrown/",
  lang: "en-US",
  cleanUrls: true,

  // External article drafts (dev.to / Medium) live in the repo for review but
  // must not ship as orphan pages on the docs site.
  srcExclude: ["article-*.md"],

  // The API reference under /api/ is generated by TypeDoc and copied in at build
  // time; its cross-references use relative links TypeDoc resolves itself.
  ignoreDeadLinks: [/^\/api\//, /^\.\/index$/, /^\.\/[a-z-]+$/, /^\.\.\//],

  sitemap: {
    hostname: "https://btravstack.github.io/unthrown/",
  },

  // Per-page canonical URL + Open Graph / Twitter title & description, so every
  // page shares a correct preview and avoids duplicate-content ambiguity.
  transformPageData(pageData) {
    if (!pageData.relativePath.endsWith(".md")) {
      return;
    }

    const normalizedPath = pageData.relativePath.replace(/^\/+/, "");
    // cleanUrls is true, so the public URL has no `.html` extension: strip
    // `index.md` to the directory and any other `.md` to the bare route.
    const canonicalUrl = `https://btravstack.github.io/unthrown/${normalizedPath}`
      .replace(/index\.md$/, "")
      .replace(/\.md$/, "");

    pageData.frontmatter ??= {};
    pageData.frontmatter.head ??= [];

    // The /api/ pages (except the hand-written overview) are TypeDoc output copied
    // in at build time — they have no source file in the repo, so "Edit this page"
    // would 404. docs/api/index.md is the one committed file there.
    if (pageData.relativePath.startsWith("api/") && pageData.relativePath !== "api/index.md") {
      pageData.frontmatter.editLink = false;
    }

    pageData.frontmatter.head.push(["link", { rel: "canonical", href: canonicalUrl }]);

    const pageTitle = pageData.title || pageData.frontmatter.title || "unthrown";
    const pageDescription =
      pageData.description || pageData.frontmatter.description || SITE_DESCRIPTION;

    pageData.frontmatter.head.push(
      ["meta", { property: "og:url", content: canonicalUrl }],
      ["meta", { property: "og:title", content: pageTitle }],
      ["meta", { property: "og:description", content: pageDescription }],
      ["meta", { name: "twitter:title", content: pageTitle }],
      ["meta", { name: "twitter:description", content: pageDescription }],
    );
  },

  themeConfig: {
    logo: { light: "/logo-light.svg", dark: "/logo-dark.svg" },

    nav: [
      { text: "Guide", link: "/guide/why-unthrown" },
      { text: "API", link: "/api/" },
      {
        text: "Changelog",
        link: "https://github.com/btravstack/unthrown/releases",
      },
      // Back to the btravstack hub (links the docs up to the landing page).
      { text: "btravstack", link: "https://btravstack.github.io/" },
    ],

    sidebar: {
      "/guide/": [
        {
          text: "Introduction",
          items: [
            { text: "Why unthrown?", link: "/guide/why-unthrown" },
            { text: "Comparison", link: "/guide/comparison" },
            {
              text: "Migrating from neverthrow",
              link: "/guide/migrating-from-neverthrow",
            },
            { text: "From try/catch", link: "/guide/from-try-catch" },
            { text: "Getting Started", link: "/guide/getting-started" },
            { text: "Core Concepts", link: "/guide/core-concepts" },
          ],
        },
        {
          text: "Working with Results",
          items: [
            { text: "The Defect Channel", link: "/guide/the-defect-channel" },
            { text: "Boundaries & Qualification", link: "/guide/boundaries" },
            { text: "Async Results", link: "/guide/async-results" },
            { text: "Do Notation", link: "/guide/do-notation" },
            { text: "Choosing a Combinator", link: "/guide/choosing-a-combinator" },
            { text: "Recipes", link: "/guide/recipes" },
          ],
        },
        {
          text: "Error Modeling",
          items: [{ text: "Tagged Errors", link: "/guide/tagged-errors" }],
        },
        {
          text: "Ecosystem",
          items: [
            { text: "Testing", link: "/guide/testing" },
            { text: "Pattern Matching", link: "/guide/pattern-matching" },
            { text: "Prisma", link: "/guide/prisma" },
            { text: "oRPC", link: "/guide/orpc" },
            { text: "Linting", link: "/guide/linting" },
            { text: "Interop", link: "/guide/interop" },
            {
              text: "Validation (standard-schema)",
              link: "/guide/interop#standard-schema-—-validators-as-results",
            },
          ],
        },
      ],
      "/api/": [
        {
          text: "API Reference",
          items: [
            { text: "Overview", link: "/api/" },
            { text: "unthrown", link: "/api/core/" },
            { text: "@unthrown/vitest", link: "/api/vitest/" },
            { text: "@unthrown/pattern", link: "/api/pattern/" },
            { text: "@unthrown/effect", link: "/api/effect/" },
            { text: "@unthrown/neverthrow", link: "/api/neverthrow/" },
            { text: "@unthrown/boxed", link: "/api/boxed/" },
            { text: "@unthrown/standard-schema", link: "/api/standard-schema/" },
            { text: "@unthrown/prisma", link: "/api/prisma/" },
            { text: "@unthrown/orpc", link: "/api/orpc/" },
          ],
        },
      ],
    },

    socialLinks: [
      { icon: "github", link: "https://github.com/btravstack/unthrown" },
      { icon: "npm", link: "https://www.npmjs.com/package/unthrown" },
    ],

    footer: {
      message: "Released under the MIT License.",
      copyright: `Copyright © ${new Date().getFullYear()} Benoit TRAVERS`,
    },

    search: {
      provider: "local",
    },

    // The single-page core API reference is a long scroll; surfacing h3s in the
    // right-rail outline is what makes it navigable.
    outline: { level: [2, 3] },

    editLink: {
      pattern: "https://github.com/btravstack/unthrown/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },
  },

  vite: {
    // @btravstack/theme's entry imports `vitepress/theme` (which pulls in `.css`)
    // and its own `style.css`. VitePress externalizes node_modules deps in the SSR
    // build, so Node's ESM loader would hit those `.css` files and throw
    // ERR_UNKNOWN_FILE_EXTENSION. Bundling the theme through Vite handles the CSS.
    ssr: { noExternal: ["@btravstack/theme"] },
  },

  head: [
    ["link", { rel: "icon", type: "image/svg+xml", href: "/unthrown/logo.svg" }],
    ["meta", { name: "author", content: "Benoit TRAVERS" }],
    ["meta", { name: "robots", content: "index, follow" }],
    ["meta", { name: "application-name", content: "unthrown" }],
    [
      "meta",
      {
        name: "keywords",
        content:
          "typescript, result, error handling, errors as values, neverthrow, effect, railway oriented programming, tagged error, defect, panic, type-safe",
      },
    ],
    // Open Graph — og:title/description/url are added per page in transformPageData
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:site_name", content: "unthrown" }],
    ["meta", { property: "og:locale", content: "en_US" }],
    [
      "meta",
      { property: "og:image", content: "https://btravstack.github.io/unthrown/og-unthrown.png" },
    ],
    ["meta", { property: "og:image:type", content: "image/png" }],
    ["meta", { property: "og:image:width", content: "1200" }],
    ["meta", { property: "og:image:height", content: "630" }],
    [
      "meta",
      {
        property: "og:image:alt",
        content: "unthrown — explicit errors as values, for TypeScript",
      },
    ],
    // Twitter Card
    ["meta", { name: "twitter:card", content: "summary_large_image" }],
    [
      "meta",
      { name: "twitter:image", content: "https://btravstack.github.io/unthrown/og-unthrown.png" },
    ],
    [
      "meta",
      {
        name: "twitter:image:alt",
        content: "unthrown — explicit errors as values, for TypeScript",
      },
    ],
    // JSON-LD structured data for better SEO
    [
      "script",
      { type: "application/ld+json" },
      JSON.stringify({
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        name: "unthrown",
        description: SITE_DESCRIPTION,
        applicationCategory: "DeveloperApplication",
        operatingSystem: "Cross-platform",
        offers: {
          "@type": "Offer",
          price: "0",
          priceCurrency: "USD",
        },
        url: "https://btravstack.github.io/unthrown/",
        author: {
          "@type": "Person",
          name: "Benoit TRAVERS",
        },
        programmingLanguage: {
          "@type": "ComputerLanguage",
          name: "TypeScript",
          url: "https://www.typescriptlang.org/",
        },
        keywords: "TypeScript, error handling, errors as values, Result, type-safe",
      }),
    ],
    // WebSite JSON-LD for proper site name display in Google search
    [
      "script",
      { type: "application/ld+json" },
      JSON.stringify({
        "@context": "https://schema.org",
        "@type": "WebSite",
        name: "unthrown",
        url: "https://btravstack.github.io/unthrown/",
      }),
    ],
    // Organization JSON-LD for logo display in Google search
    [
      "script",
      { type: "application/ld+json" },
      JSON.stringify({
        "@context": "https://schema.org",
        "@type": "Organization",
        name: "unthrown",
        url: "https://btravstack.github.io/unthrown/",
        logo: {
          "@type": "ImageObject",
          url: "https://btravstack.github.io/unthrown/logo.svg",
        },
        sameAs: ["https://github.com/btravstack/unthrown"],
      }),
    ],
  ],
});
